#!/bin/sh

filter_out_cwd_markers() {
    sed -r 's/\ \.\//\ /'
}

checksum_cmd_name() {
    echo "${1}sum" | tr [:upper:] [:lower:]
}

checksum_file_name() {
    echo "${1}SUMS" | tr [:lower:] [:upper:]
}

die() {
    echo "$*" >&2
    exit 1
}

usage() {
    die 'Usage: dirsum [-r|--recursively] HASH'
}

HASH=$1

[ -n "$HASH" ] \
    || HASH='md5'

CHECKSUM_CMD_NAME=`checksum_cmd_name $HASH`

which $CHECKSUM_CMD_NAME >/dev/null 2>&1 \
    || die "Error: No hashsum function '$CHECKSUM_CMD_NAME' found."

CHECKSUM_FILE_NAME=`checksum_file_name $HASH`

echo "Using '$CHECKSUM_CMD_NAME' to calculate hashsums"

find . -type f ! -regex '.*/[A-Z]+[0-9]*SUMS' -print0 \
    | sort -z \
    | xargs -0 $CHECKSUM_CMD_NAME \
    | filter_out_cwd_markers >$CHECKSUM_FILE_NAME
