#!/bin/sh

XDBUS_EXPORTS="${HOME}/.Xdbus"

# Export the dbus session address on startup so it can be used by cron
env | grep DBUS_SESSION_BUS_ADDRESS >"${XDBUS_EXPORTS}"
echo 'export DBUS_SESSION_BUS_ADDRESS' >>"${XDBUS_EXPORTS}"

# Export XAUTHORITY value on startup so it can be used by cron
env | grep XAUTHORITY >>"${XDBUS_EXPORTS}"
echo 'export XAUTHORITY' >>"${XDBUS_EXPORTS}"

chmod 600 $HOME/.Xdbus
