#!/bin/sh

HOMEBIN=$(dirname "$0")
HOMESECRETS="${HOMEBIN}"/.secrets
[ -e "${HOMESECRETS}" ] && . "${HOMESECRETS}"

#LVEE_LOGIN
#LVEE_PASSWORD

COOKIES=/tmp/.cookies.lvee

prepare_cookies() {
    wget --quiet -O /dev/null \
        --save-cookies ${COOKIES} \
        --post-data "login=${LVEE_LOGIN}&password=${LVEE_PASSWORD}&remember_me=1" \
        "https://lvee.org/en/session"
}

cleanup() {
    rm -f ${COOKIES}
}

lvee_particip() {
    echo $(( $( \
        wget --quiet -O- \
        --load-cookies ${COOKIES} \
        "https://lvee.org/en/conference_registrations/LVEE%20${1}" \
        | grep -c '<tr' \
        ) - 1 ))
}

lvee_particip_winter() {
    echo $(( $( \
        wget --quiet -O- \
        --load-cookies ${COOKIES} \
        "https://lvee.org/en/conference_registrations/LVEE%20Winter%20${1}" \
        | grep -c '<tr' \
        ) - 1 ))
}

print_lvee_year() {
    printf '%s: %3s %3s\n' "${1}" $(format_no "${2}") $(format_no "${3}")
}

format_no() {
    if [ "$1" = "-1" ]; then
        echo '-'
    else
        echo $1
    fi
}

prepare_cookies
trap cleanup EXIT

if [ $# -eq 0 ]; then
    lvee_particip `date +%Y`
else
    while [ -n "${1}" ]; do
        lvee_summer=$(lvee_particip "${1}")
        lvee_winter=$(lvee_particip_winter "${1}")
        print_lvee_year "${1}" "${lvee_winter}" "${lvee_summer}"
        shift
    done
fi

cleanup

