#!/bin/sh

exec >/dev/null 2>&1

CURRENT_LAYOUT=`setxkbmap -print | sed -r -n 's/^.*pc\+([^+]{2})\+.*$/\1/p'`

case "${CURRENT_LAYOUT}" in
    by)
        setxkbmap -layout "us,ru"
        ;;
    *)
        setxkbmap -layout "by"
        ;;
esac

