#!/bin/bash

TITLE='Yell'
MESSAGE=''

if [ "-t" = "$1" ]; then
    TITLE="$2"
    shift && shift
fi

MESSAGE="$*"

escape_for_osa() {
    echo "$*" | sed 's/"/\\"/g'
}

notify_macos() {
    local title="$1" && shift
    local message=$(escape_for_osa "$*")

    osascript <<EOS
set Message to "${message}"
set Title to "${title}"
display notification Message with title Title
EOS
}

case `uname` in
    'Darwin')
        notify_macos "${TITLE}" "${MESSAGE}"
        ;;
    *)
        echo "No handler to notify" >&2
        exit 1
esac

